---
Read:
    user: admin
    password: example
    host: some-mongo
    port: 27017
    db: dummy
    collection: random_password
    
Write:
    user: admin
    password: example
    host: some-mongo
    port: 27017
    db: dummy
    collection: test_result
...
